services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - backend_db:/app/db
      - static_volume:/app/static
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api/
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/django_static:ro
    depends_on:
      - backend
    restart: always

volumes:
  backend_db:
  static_volume:
